### ISSUE TITLE
Use of Apriltags component

### ISSUE THREAD

**Issue by alexlss** [dbcesar/perception-orogen-apriltags#16]
In an application we have tried to use Apriltags component to recognize a tag in a subsea simulated scenario.
We provide four images given as input to the component. In the AprilTags1.jpg the tag has been recognized. In the other three images it hasn't been recognized.
We provide also the parameters files used for configuring the component.
Why doesn't the component work in the other three cases? Where we are wrong?

Apriltag1.jpg
![apriltags1](https://user-images.githubusercontent.com/33420476/32833162-3f57d410-c9fe-11e7-9d5f-b415f93474c9.jpg)

Apriltags2.jpg
![apriltags2](https://user-images.githubusercontent.com/33420476/32833189-56fb01c8-c9fe-11e7-9e53-7c1196e21a8f.jpg)

Capture3.png
![capture3](https://user-images.githubusercontent.com/33420476/32833341-e0a8268a-c9fe-11e7-86f5-fd937e635516.png)

Capture1.png
![capture1](https://user-images.githubusercontent.com/33420476/32833342-e0d54b1a-c9fe-11e7-81a9-ecd067f8b17d.png)

Config file for Apriltag1.jpg and Apriltag2.jpg
[apriltags::Task.yml.txt](https://github.com/rock-perception/perception-orogen-apriltags/files/1474451/apriltags.Task.yml.txt)

Config file for Capture1.png and Capture3.png
[apriltags::Task.yml (2).txt](https://github.com/rock-perception/perception-orogen-apriltags/files/1474457/apriltags.Task.yml.2.txt)

**Comment by doudou** [comment]
Now that I see the pictures, I have a theory:
- the aprilags need to be on a flat surface. The way you hold the sheet of paper deforms it a lot
- one important aspect of the tag is that the exterior is always a rim of white around a rim of black. The blue images don't have this alternance (they're lacking the rim of white).

Amiright, @dbcesar ?

**Comment by fraeu** [comment]
Asap we will change simulator to have the white border around the tag to test it

**Comment by dbcesar** [comment]
> Amiright, @dbcesar ?

Yes. 

Generally speaking, Apriltag's searching algorithm looks for four-sided shapes on the image. Afterwards, it divides these polygon in 8x8 grid to check the binary codes (if small square is mostly black, code is 0, if it is mostly white, code is 1). The *first* test to reject false candidates is to look to the outer bits and see if all of them are black. Only if it pass to this test, it looks to the inner bits in order to validate apriltags ID. 

In summary, on the "Apriltags2.jpg" the image is distorted, then I think it did't classify the big black border as a four-sided shape  (if distortion is caused by camera, which is not the case, you have to rectify image before detection). On the other images, there is no a outer black border on the image, that is why apriltags are not being detected. 

> Asap we will change simulator to have the white border around the tag to test it

besides the white, it has have the black border as well

**Comment by fraeu** [comment]
Now we have tested with the new simulator and it's work
thank you
